input {
  file {
    path => "/var/log/messages-incident"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  grok {
    patterns_dir => "/etc/logstash/patterns/"
    match => { "message" => "%{SYSLOGBASE_PERSO}" }
  }

  mutate {
    copy => { "@timestamp" => "[event][created]" }
  }
  date {
    match => [ "timestamp", "MMM dd HH:mm:ss" ]
    timezone => "Europe/Paris"
  }

  if [processus] == "java-app" {
    grok {
      match => { "message_parse" => "%{LOGLEVEL:niveau} %{DATA}Heap usage at %{NUMBER:heap}%" }
    }
  }

  if [processus] == "backup-job" {
    grok {
      match => {
        "message_parse" => [
          "Writing archive... %{NUMBER:[backup][size]}(?<[backup][unit]>[A-Za-z]+) written",
          "Starting %{DATA:[backup][type]} backup to %{PATH:[backup][path]}",
          "Backup failed: %{GREEDYDATA:[backup][error]}",
          "Cleanup incomplete, %{DATA} in %{PATH:[backup][path]}"
        ]
      }
    }
    if "_grokparsefailure" not in [tags] {
      mutate {
        convert => { "[backup][size]" => "integer" }
        add_field => { "[backup][size_with_unit]" => "%{[backup][size]}%{[backup][unit]}" }
      }
      bytes {
        source => "[backup][size_with_unit]"
        target => "[backup][bytes]"
      }
      mutate {
        remove_field => [ "[backup][size_with_unit]" ]
      }
    }
  }

  if [processus] == "kernel" {
    grok {
      match => { "message_parse" => "%{DATA:[fs][format]} %{LOGLEVEL:[fs][level]}: %{GREEDYDATA:details}" }
    }
  }
}

output {
  if "_grokparsefailure" in [tags] {
    file {
      path => "/home/vinz/logstash-lab/logstash_failed_logs.log"
    }
  } else {
    stdout {}
  }
}
