input {
  file {
    path => "/home/vinz/deployer_filebeat.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

#Input en direct pour debug et reload la conf
#input {
#    exec {
#      command => "echo -n 'rh8103.localdomain         : ok=5    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0'"
#      interval => 5
#    }
#}

filter {
    #Drop les lignes vides
    if [message] == "" {
      drop {}
    }

    #Gestion des lignes titres - tasks ou play
    if [message] =~ "^PLAY \[" or [message] =~ "^TASK \[" {
        grok {
            match => { "message" => "%{WORD:[ansible][type]} \[%{DATA:[ansible][name]}\] \*%{GREEDYDATA}" }
        }
    }

    #Gestion des lignes d'executions 
    #if [message] =~ "^changed: " or [message] =~ "^ok: " {
    else if [message] =~ "^[a-z]+: " {
        grok { 
            match => { "message" => "%{WORD:[ansible][state]}: \[%{HOSTNAME:[ansible][target]}\]%{GREEDYDATA}"}
        }
    }

    #Gestion ligne recap 
    else if [message] =~ ".*ok=.*changed=" {
        grok { 

#        version bricolage sans kv
#        match => { "message" => "%{HOSTNAME:[ansible][target]}%{SPACE}: ok=%{NONNEGINT:[ansible][ok]}%{SPACE}changed=%{NONNEGINT:[ansible][changed]}%{SPACE}unreachable=%{NONNEGINT:[ansible][unreachable]}%{SPACE}failed=%{NONNEGINT:[ansible][failed]}%{SPACE}skipped=%{NONNEGINT:[ansible][skipped]}%{SPACE}rescued=%{NONNEGINT:[ansible][rescued]}%{SPACE}ignored=%{NONNEGINT:[ansible][ignored]}%{GREEDYDATA}" }
            

#       Preparation pour kv
         match => { "message" => "%{HOSTNAME:[ansible][target]}%{SPACE}: %{GREEDYDATA:recap_line}" } 
        }

        kv {
          source => "recap_line"
          field_split => "\s+"
          value_split => "="
          target => "[ansible]"
        }
#       nettoyage du champ tmp
        mutate {
            remove_field => "recap_line"
        }

        mutate {
            convert => { "[ansible][ok]" => "integer" }
            convert => { "[ansible][changed]" => "integer" }
            convert => { "[ansible][unreachable]" => "integer" }
            convert => { "[ansible][failed]" => "integer" }
            convert => { "[ansible][skipped]" => "integer" }
            convert => { "[ansible][rescued]" => "integer" }
            convert => { "[ansible][ignored]" => "integer" }
        }

    }

    else {
        drop {}
    }
   

}

output {
  if "_grokparsefailure" in [tags] {
    file {
      path => "/home/vinz/logstash-lab/failed_logs_ansible_v.log"
    }
  } else {
    file {
      path => "/home/vinz/logstash-lab/ok_logs_ansible_v.log"
    }
  }
}

#Output stdout pour debug
#output {
#    stdout{}
#}
