input {
  stdin {}
}

filter {
  dissect {
    mapping => { "message" => "%{timestamp} %{+timestamp} %{+timestamp} %{hostname} %{prog}[%{pid}]: %{msg}" }
  }
  mutate {
    copy => { "@timestamp" => "[event][created]" }
  }
  date {
    match => [ "timestamp", "MMM dd HH:mm:ss" ]
    timezone => "Europe/Paris"
  }
}

output {
  stdout {}
}
