input {
  stdin {}
}

filter {
  grok {
    match => { "message" => "%{SYSLOGTIMESTAMP:timestamp} %{HOSTNAME:hostname} %{PROG:processus}(?:\[%{POSINT}\])?: %{GREEDYDATA:message_parse}" }
  }

  if [processus] == "kernel" {
      grok {
        match => { "message_parse" => "%{DATA:[fs][format]} %{LOGLEVEL:[fs][level]}: %{GREEDYDATA:details}" }
      }
  }
}

output {
  if "_grokparsefailure" in [tags] {
    file {
      path => "/home/vinz/logstash-lab/logstash_failed_logs.log"
   }
  } else {
    stdout {}
  }
}
