input {
  stdin {}
}

filter {
  grok {
    match => { "message" => "%{SYSLOGTIMESTAMP:timestamp} %{HOSTNAME:hostname} %{WORD:processus}(?:\[%{POSINT}\])?: %{GREEDYDATA:message_parse}" }
  }
}

output {
  stdout {}
}
