input {
  stdin {}
}

filter {
  grok {
    match => { "message" => "%{SYSLOGTIMESTAMP:timestamp} %{HOSTNAME:hostname} %{PROG:processus}(?:\[%{POSINT}\])?: %{GREEDYDATA:message_parse}" }
  }

  if [processus] == "java-app" {
    grok {
      match => { "message_parse" => "%{LOGLEVEL:niveau} %{DATA}Heap usage at %{NUMBER:heap}%" }
    }
  }
}

output {
  stdout {}
}
