input {
  stdin {}
}

filter {
  grok {
    match => { "message" => "%{SYSLOGTIMESTAMP:timestamp} %{HOSTNAME:hostname} %{PROG:processus}(?:\[%{POSINT}\])?: %{GREEDYDATA:message_parse}" }
  }

  if [processus] == "backup-job" {
    grok {
      match => { "message_parse" => "Writing archive... %{NUMBER:[backup][size]}(?<[backup][unit]>[A-Za-z]+) written" }
    }
  }
}

output {
  stdout {}
}
