[ ca ]
default_ca = CA_default

[ CA_default ]
# --- Parametres communs ---
dir               = /home/vinz/ca
database          = $dir/ca.db        # Partagé
serial            = $dir/ca.db.serial # Partagé
new_certs_dir     = $dir/newcerts     # Partagé
certificate       = $dir/vinz-lab.crt
private_key       = $dir/vinz-lab.key
default_days      = 365
default_md        = sha256
policy            = policy_anything
copy_extensions = copy

[ policy_anything ]
commonName              = supplied
stateOrProvinceName     = optional
countryName             = optional
emailAddress            = optional

# ==========================================
# PROFILE 1 : Configuration pour Serveur
# ==========================================
[ server ]
authorityKeyIdentifier = keyid,issuer
basicConstraints       = CA:FALSE
keyUsage               = digitalSignature, keyEncipherment
extendedKeyUsage       = serverAuth

# ==========================================
# PROFILE 2 : Configuration pour Client
# ==========================================
[ client ]
authorityKeyIdentifier = keyid,issuer
basicConstraints       = CA:FALSE
keyUsage               = digitalSignature, keyEncipherment
extendedKeyUsage       = clientAuth

