[logstash_hosts]
rocky.localdomain ansible_python_interpreter=/usr/bin/python3.9
[es_hosts]
rocky.localdomain ansible_python_interpreter=/usr/bin/python3.9

[filebeat_hosts]
rh8103.localdomain ansible_python_interpreter=/usr/bin/python3.12
